name: custom_bingo
description: A Very Good Project created by Very Good CLI.
version: 1.0.2+3
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  collection: ^1.19.1
  dart_mappable: ^4.5.0
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  # fluttertoast: ^8.2.12
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  intl: any
  logger: ^2.5.0
  shared_preferences: ^2.5.3
  state_beacon: ^1.0.0
  drops: ^0.0.5
  share_plus: ^10.1.4
  uuid: ^4.5.1
  animated_text_kit: ^4.2.3
  in_app_review: ^2.0.10
  auto_size_text: ^3.0.0
  flutter_confetti: ^0.5.1
  package_info_plus: ^8.3.0
  screenshot: ^3.0.0
  phosphor_flutter: ^2.1.0
  userorient_flutter: ^1.2.0
  animated_to: ^0.4.0

dev_dependencies:
  build_runner: ^2.4.15
  dart_mappable_builder: ^4.6.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21

# dart run flutter_native_splash:create
flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove

  # IMPORTANT NOTE: These parameter do not affect the configuration of Android 12 and later, which
  # handle splash screens differently that prior versions of Android.  Android 12 and later must be
  # configured specifically in the android_12 section below.

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FFFFFF"

  image: assets/app_icon.png
