# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  
  build_android:
    cmds:
      - flutter build aab --release --flavor production -t lib/main_production.dart
  
  build_ios:
    cmds:
      - flutter build ios -t lib/main_production.dart --flavor production --config-only --release
  
  launch_icons:
    cmds:
      - flutter pub run flutter_launcher_icons
  
  native_splash:
    cmds:
      - flutter pub run flutter_native_splash:create
  
